apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
        name: course-config
        key: course
    - name: duration
      alueFrom:
        configMapKeyRef:
        name: course-config
        key: duration