---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    server: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  server: nginx-service
spec:
  selector:
    server: nginx-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels: 
    purpose: debug
spec:
  containers:
  - name: almalinux
    image: almalinux
    command: ["sleep","100000"]